name = "Matcha Gaming Squared"
author = "wong"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b98ed00bb5d169275d39184e27a41e825a7f3397378cf7bab3af5608c39e90ac"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
