name = "Matcha Gaming Squared"
author = "wong"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e078161844d7e782c50e858110fd0a47e9d553cb1f4f9bdb1da5c44f28449d7a"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
