
# Should space-clicking move all items even if an empty slot was clicked?
allowBulkTransferAllOnEmptySlot = false

# Should space-clicking armor in the inventory swap to all matching armor?
bulkTransferArmorSets = true

# Should shift-ctrl-drop-clicking drop all items of the same type at once?
enableBulkDrop = true

# Should shift-ctrl-clicking move all items of the same type at once?
enableBulkTransfer = true

# Should space-clicking an item move all items from that inventory at once?
enableBulkTransferAll = true

# Should control-space-clicking an item move one of each item from that inventory at once?
enableBulkTransferSingle = true

# Should picked up items automatically be placed into matching bundles?
enableBundleAutoFill = true

# Should holding click or right-click with a bundle empty or insert hovered slots?
enableBundleDrag = true

# Should holding shift and moving your mouse over items quick-transfer them without requiring each to be clicked?
enableShiftDrag = true

# Should ctrl-clicking only move one item at a time instead of the full stack?
enableSingleTransfer = true

# Should depleted block stacks automatically be replaced from the inventory?
enableStackRefill = true

# Should broken tools automatically be replaced from the inventory?
enableToolRefill = true

# Use the client implementation even on servers that have the mod installed - only useful for development purposes.
forceClientImplementation = false

# Choose how middle-click inventory sorting should behave.
inventorySorting = "creative"

